application: acampsriotest
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "7d"
  
handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /font
  static_dir: font

- url: /.*
  script: controller.application
